### ISSUE TITLE
unicode seems to hang up

### ISSUE THREAD

**Issue by spacejam** [ticki/termion#75] opened 2016-11-27 22:29 UTC
https://github.com/spacejam/void/issues/6
reproduced on urxvt & xterm on linux 4.8.10 with german keyboard `setxkbmap de`

**Comment by iqualfragile** [comment] 2016-11-27 22:38
also works on the suckless st

**Comment by iqualfragile** [comment] 2016-11-27 22:41
not limited to umlauts, also greek letters(ελτ) and other non-ascii-symbols(✔✔).
maybe something about the bytes? ascii is one byte the others are more then that.

**Comment by gyscos** [comment] 2016-12-04 22:41
Seems to be caused by `input.rs:62` keeping some continuation bytes as leftover, even though they're consumed by `parse_event()`.

**Comment by gyscos** [comment] 2016-12-18 08:31
Should be fixed now.

**Comment by ticki** [comment] 2016-12-18 18:21
Yup.

**Closed by ticki** 2016-12-18 18:21 UTC

**Comment by spacejam** [comment] 2016-12-18 20:34
Thanks folks!
